### ISSUE TITLE
人のプロフィールに記念日/命日を追加する

### ISSUE THREAD

**Issue by suztomo** [suztomo/Memorio#17]
結婚記念日、命日など。

命日は特別で、故人のことを記録する際に命日がないとその人の年齢が毎年増やされてしまう。

作ったら通知: 1/21日のメール

**Comment by kuboon** [comment]
生きてたら何歳、みたいのはあるので年齢を止めるのはあまり優先度は高くなく、命日はタグでつければ済む気がします。 （私は実際にそれで何人かの命日を記録しました

結婚式の日、とかも、その日の記録に「結婚式」タグをつけるとか、「結婚式 #記念日」のようにすれば検索して見つけられるので良い気がします

毎年のリマインドみたいのをこのアプリに求めるか？というと、私はカレンダーで済ませてしまいそう。

**Comment by kuboon** [comment]
今年で結婚何周年、とか、没後何年、みたいのを表示するのは、カレンダーでは難しいので面白いかも。

**Comment by suztomo** [comment]
今週は記念日を作り始めます。

> 「享年（きょうねん）」とは、天から享（う）けた年数という意味で、数え年で考えます。

https://www.ishichou.co.jp/static/knowledge/gravestone/detail04.html

**Comment by suztomo** [comment]
昨日リリースした0.22.1にて命日を入力できるようになりました。
