### ISSUE TITLE
ios widget 対応

### ISSUE THREAD

**Issue by kuboon** [suztomo/Memorio#22]
![image](https://user-images.githubusercontent.com/48445/104598387-dc4e7580-56b9-11eb-9584-7c26a0583d15.jpeg)

こんな感じで人物アイコンが並んで、タップですぐその人のメモを書けるのが欲しいです

**Comment by suztomo** [comment]
これも良いアイデアありがとうございます。僕も欲しいです。

**Comment by suztomo** [comment]
Home Widgetの勉強を始めました。まずは写経から。
https://twitter.com/MemorioApp/status/1352477097084780546

**Comment by suztomo** [comment]
出来る気がしてきました。

https://developer.apple.com/videos/play/wwdc2020/10033/

Apple Human Interface Guideline: Widget

https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/widgets

# Tap Targets

> Ensure that tapping your widget opens your app at the right location. When people tap your widget, it deep-links into your app, where you can offer details and actions that are directly related to the widget’s content. For example, when people tap a Stocks symbol widget, the Stocks app opens to a page that displays information about that symbol. Similarly, when people tap a small Stocks watchlist widget, the app opens to show the complete watchlist.

> A small widget supports a single tap target, but medium and large widgets can offer multiple targets. 

具体的にはLinkクラスを使うみたい。https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension

> For widgets using systemMedium or systemLarge, add one or more Link controls to your widget’s view hierarchy.

Home Widgetの仕組みは分かりました。あとはメモリオに組み込む作業です。

https://twitter.com/memorioapp/status/1353164124709117952

**Comment by suztomo** [comment]
@kuboon 中くらいサイズのヴィジェットに人を4人並べる件ですが、その4人はどう選ばれるべきだと思いますか？

自分の想定しているやり方は"よくメモを書くひと"へのショートカットなので、"最近更新された順"で4人選べばいいのではないかと思っております。

**Comment by kuboon** [comment]
それでokです！

**Comment by suztomo** [comment]
はい、ではこれでやってみます。

**Comment by suztomo** [comment]
出来てきました! もうすぐリリースです。

![image](https://user-images.githubusercontent.com/28604/105934703-afd21c00-601e-11eb-9f68-4b11691f76de.jpeg)

**Comment by suztomo** [comment]
@kuboon 今日リリースされた0.20.0にバージョンアップしてからアプリを開くとヴィジェットが使えるようになります。フィードバックありがとうございました。
