### ISSUE TITLE
インポートして削除した人物は再インポート出来なくなる

### ISSUE THREAD

**Issue by kuboon** [suztomo/Memorio#24]
再インポートしたい。
もしくは、 memorio で作成した人物に後から連絡先をリンクしたい

**Comment by suztomo** [comment]
再インポートする使い方が思い当たらず、間違って同じ人を2人追加しないように一度追加した人をまた入れないようにしてありますり

どのような使い方でこの問題に当てはまりましたか？

**Comment by suztomo** [comment]
# 実装方針

ひとの情報に連絡先から登録されたidをデバイス固有のIDとともに保存してみる。デバイス固有のIDを付加しないと連絡先ID"5"の人が複数の端末に存在するときにインポートできなくなる。

https://stackoverflow.com/a/49187284/975074 によるとdevice_info プラグインがそのIDを提供してくれるよう。

しかし連絡先インポートなんて１時的にしか使わないから不要か。

**Comment by suztomo** [comment]
一度入れた人を入れないようにする仕組みを外しました。
